name       : brscan4
version    : 0.4.4_4
release    : 2
source     :
    - http://download.brother.com/welcome/dlf006648/brscan4-0.4.4-4.x86_64.rpm : c21c3894b0bb8fe6f142e179b2e75f0b541174836796177965321d3c205075d7
license    : Distributable
component  : drivers
extract    : no
strip      : no
summary    : Brscan4 drivers for Brother scanners
description: |
    Brscan4 provides a variety of scanning drivers for various Brother scanners and multi-function printers.
    Note that some portions are binary and provided for hardware enablement so may not meet typical Solus packaging standards for paths.
builddeps  :
    - pkgconfig(libusb)
    - rpm
install    : |
    for i in $sources/*.rpm; do
        rpm2cpio ${i} | cpio -idmv
    done

    # Install files
    install -d -m 00755 $installdir
    mv etc $installdir/
    mv opt $installdir/
    mv usr $installdir/

    install -d -m 00755 $installdir/etc/sane.d/dll.d
    echo "brother4" > $installdir/etc/sane.d/dll.d/brscan4
    install -D -m 00644 $pkgfiles/70-brscan4.rules $installdir/%libdir%/udev/rules.d/70-brscan4.rules

    # rm brsanenetdevice4.cfg you can generate it
    rm -rf $installdir/opt/brother/scanner/brscan4/brsanenetdevice4.cfg
