name       : brscan4
version    : 0.4.11_1
release    : 3
source     :
    - https://download.brother.com/welcome/dlf105203/brscan4-0.4.11-1.x86_64.rpm : 7d7dcbe8349ae4d4ab816e4551017f2f1fd9fd6bf3f4f3c570fbd9576248dd9f
license    : Distributable
component  : drivers
extract    : no
strip      : no
summary    : Brscan4 drivers for Brother scanners
description: |
    Brscan4 provides a variety of scanning drivers for various Brother scanners and multi-function printers.
    Note that some portions are binary and provided for hardware enablement so may not meet typical Solus packaging standards for paths.
builddeps  :
    - pkgconfig(libusb)
    - rpm

install    : |
    for i in $sources/*.rpm; do
        rpm2cpio ${i} | cpio -idmv
    done

    $pkgfiles/create-udev-rules $workdir/opt/brother/scanner/brscan4/{Brsane4.ini,models4/*.ini} > 70-brscan4.rules

    chmod 644 $workdir/opt/brother/scanner/brscan4/{setupSaneScan4,udev_config.sh}

    # Install files
    install -d -m 00755 $installdir
    mv etc $installdir/
    mv opt $installdir/
    mv usr $installdir/

    install -d -m 00755 $installdir/etc/sane.d/dll.d
    echo "brother4" > $installdir/etc/sane.d/dll.d/brother4.conf

    install -D -m 00644 ./70-brscan4.rules $installdir/%libdir%/udev/rules.d/70-brscan4.rules

    # rm brsanenetdevice4.cfg you can generate it
    rm -rf $installdir/opt/brother/scanner/brscan4/brsanenetdevice4.cfg
